### ISSUE TITLE
Internet Uplink

### ISSUE THREAD

**Issue by erdnusskeks** [railscamp/railscamp-germany-2014#15]

**Comment by eimann** [comment]
Yes! Here and screaming for excitement!

**Comment by eimann** [comment]
As last year, we've equipment available:

2x 65cm dishes
2x radio module (up to 30km with line of sight, 100Mbps)
2x GPS antenna for synchronization
2x 30m Ethernet cable (orange)
2x Power supply
1x Cisco Router to be placed at the FH Koeln building

Further we will make the following available:
1x /20 IPv4 network
1x /48 IPv6 network

Installation and removal will be done by us.

**Comment by jhilden** [comment]
Since we have a date now (26-28 September), let's start planning this.

From old emails I have these information on what we will need from the FH:
- Access to the roof on Friday during the day.  For how long?  1-2 hours?
- Place to mount the dish (last year: "15. Ebene an einem 2m hohen 100mm Mast in
  östlicher Richtung")
- Power outlet within x meters of the dish
- Ethernert port with access to the internet within x meters
- Place to put our routes (with power outlet) (last year: "DV-Verteilerraum auf der 7. Ebene")
- Access to the roof on Monday for tear down

Can you check/complete the list @badboy @eimann ?

Here is a map for the radio link http://goo.gl/maps/MtRgt

Last year we had contact to christoph.wempe@fh-koeln.de, patric.rotscheroth@fh-koeln.de, dirk.hoffacker@fh-koeln.de from the Campus IT.   And Prof Noss set up the connection for us.  @koos how do we want to do it this year?

Since we have more time this year maybe we can offer a little more than just a logo to our "internet sponsors": rrbone & FH Köln.  Ideas?

**Comment by badboy** [comment]
Looks good to me. Access to the roof of the FH will be just 15 minutes (only to mount the antenna) plus 30 minutes (or so) configuring our endpoint (maybe we can get it better pre-configured this time).
Now that we know the location at Abenteuerhallen we should plan for a slightly more professional mounting on the roof.

Also this time I'll be there the whole weekend, and probably @eimann, too

**Comment by jhilden** [comment]
Very good point.  I will talk to the the maintenance guy at the Abenteuerhallen about a proper mounting setup, when I will be there the next time.

**Comment by koos** [comment]
Ich habe die FH angeschrieben und gefragt ob die uns wieder 'ne Netzanbindung geben würden. Let's see...

**Comment by jhilden** [comment]
@koos plans to meet with his FH Professor contact next Tuesday

**Comment by koos** [comment]
I've got an confirmation from the FH - they're supporting us again like next year. This is great. @eimann @badboy - I'll get in touch with you and handle the communication between you and the FH like last year if it's okay for you.

**Comment by RmMsr** [comment]
Great to hear!

**Comment by eimann** [comment]
superb! :)

**Comment by badboy** [comment]
:+1:

**Comment by erdnusskeks** [comment]
So, FH will be sailor sponsor again? I will send a tweet.

**Comment by koos** [comment]
@erdnusskeks let me clarify this in detail later this week. last year they didn't want to show up as an official sponsor.

**Comment by erdnusskeks** [comment]
Ok, I will wait for your final "go!".

**Comment by jhilden** [comment]
Last year they appeared on the website anyway:  http://2013.railscamp.de/sponsors/

I would give their sponsorship a title as well.  I guess "Internet Uplink Sponsor" would make sense.

**Comment by koos** [comment]
Hi,
wer wird sich um die Installation kümmern - bitte melden jan@railslove.com Danke!

**Comment by jhilden** [comment]
@badboy @eimann did you already get in contact with the guys from the FH.  Even though it is still some time, I think it would be good to already exchange names, contact information and talk about times for setup/teardown.

**Comment by eimann** [comment]
![foo](https://cloud.githubusercontent.com/assets/2742432/4348993/74e154ca-41a4-11e4-8da4-d6d843fbc0a9.png)

Fresnal Zone with 75m tower height @ FH and 25m roof height @ AH

**Comment by eimann** [comment]
17er wrenches needed (2x)
radios from koelnton for communication during turn-up
at least 2x binoculars

Already packed:
2x Rocket M5 + 30dBi dish
2x AirFiber 5
4x 30m Cat5e orange straight
1x ER-Pro (Cisco 2821 as Backup)

Schedule:
0830 leaving Dortmund
0945 arrival koelnton, getting the radios
1015 arrival abenteuerhallen
1025 setting up slave AF5 (@zakx and @timbuchwaldt)
1050 driving over to FH
1100 meet FH staff, climb the roof
1115 contact @zakx and @timbuchwaldt to setup AF5 link
1200 done (and working, hopefully)
