### ISSUE TITLE
Beamer / Projectors

### ISSUE THREAD

**Issue by Uepsilon** [railscamp/railscamp-germany-2014#2]
We will need several projectors for the rooms.
- [ ] Mainhall, will need a GOOD projector due to large area 
- [ ] Room 1 
- [ ] Room 2

**Comment by code-later** [comment]
Because I was asked in #21 if missed anything last year: Audio-wise everything was fine, but the beamer situation was not-acceptable. For some talks during the day there was no difference in using a beamer or not.

As it is not very nice for the speakers that their slides cannot be viewed I suggest we invest more money in this asset.

**Comment by jhilden** [comment]
Maybe @DonSchado has some time to research a better projector?

**Comment by DonSchado** [comment]
nope. 
but as far as I remember "someone else" already said he want to take care about this issue. 
can't remember who exactly. :(

**Comment by jhilden** [comment]
we could ask here:  http://www.deutschewerbewelt.de/leistungen/technologie/

this is the issue from last year:  https://github.com/railscamp/railscamp-germany-2013/issues/28

**Comment by jhilden** [comment]
@dasgib maybe

**Comment by raucao** [comment]
+1 for a brighter-than-sunlight projector! :)

**Comment by Uepsilon** [comment]
I just asked Lang AG for their prices for a 10k+ Lumen Projector. The Evoke-Guys get their projectors there, so I guess they know what they are talking about.

**Comment by Uepsilon** [comment]
Lang AG just answered, telling me that the 10k+ lumen Projector (I asked for a cheap one) is about 3300€.. Wow ;)

**Comment by jhilden** [comment]
I asked around a little bit what we could get for a budget of 200€ (w/out tax).  I think that sounds reasonable, or?

Here is what I found so far:

| Location | Beamer | Price (w/out tax) |
| --- | --- | --- |
| 51069 Köln | LCD 4500 Lumen | ~135€ |
| 52249 Eschweiler | Mitsubishi XL7100, 1024x768, 6000 Lumen, Optik 1.48-2.66:1 | € 180,- (+10€ Versand) |
| 41515 Grevenbroich | Acer P7290 mit 5000 Lumen | 120€ |

**Comment by jhilden** [comment]
@slogmen did you get any new information here?

**Comment by Uepsilon** [comment]
@nodepond gave me the lang AG as an address too.. so no luck there.. ;(

**Comment by jhilden** [comment]
Good news.  We should be able to get an 8000 Lumen projector for our budget.

**Comment by RmMsr** [comment]
So we have the main hall covered. @jhilden is that confirmed?
What is about the two small rooms? I remember some company projectors might be used. Is that settled?

**Comment by jhilden** [comment]
The big projector (Epson EB-Z8150, 8000 Lumen) for the main stage is confirmed (+ HDMI cable).   The only thing we still need is something to mount the beast (22kg) to the traverse.  If anybody has suggestions for that, otherwise we need to build something.

The beamer needs to be picked up on Friday afternoon in Deutz.  Still checking on the exact time.  Could anybody pick it up?

The Abenteurhallen have another beamer and I will bring one more beamer from Railslove.  If it should be needed I can also bring more than one beamer from Railslove, but I think 2 small + 1 big should be fine.

**Comment by eimann** [comment]
We can bring an Epson EMP-TW1000 if needed.
