### ISSUE TITLE
document with sponsoring packages  

### ISSUE THREAD

**Issue by m20io** [railscamp/railscamp-germany-2014#7]
Create Document with sponsoring options:
- Captians (1000 €)
- Lieutenants (500 €)
- Sailors (250 €)
- (Smutje, Barista, Navigator)
- (2 x 1000 € Party Sponsor)

Contant:
- describe benefits
- actions after sponsoring (Twittern)
- presentation options at camp
- taking care onside

**Comment by Uepsilon** [comment]
old sponsors and interested ones can be found in the old [titanpad](http://titanpad.com/BSc5bPt5S3)

**Comment by m20io** [comment]
Create possibility for sponsors to present themself as employers:
- jobs board
- interview sessions

**Comment by RmMsr** [comment]
We talked about the sponsoring packages and named these goals:

Main sponsors (= 8.100,00 €)
- 3 x Capain (1.200,00 €)
- 4 x Lieutenant (500,00 €)
- 10 x Sailor (250,00 €)

Topic sponsors (= 3.400,00 €)
- Food (1.000,00 €)
- Coffee (900,00 €)
- Drinks (900,00 €)
- BBQ (600,00 €)

Which would in theory bring us 11.500,00 € from sponsors.
We have currently no party sponsor because no budget exists.

More details in the [sponsors spreadshet](https://docs.google.com/spreadsheets/d/10N-HksIwP9vZE2GBcJWEl4To_cXOO42-GRy08V4bVqI/edit#gid=1791389820). Please request access if you're interested.

**Comment by RmMsr** [comment]
The alpha version of our Sponsoring brochure (in German) is ready. There will be a visually improved version sometime later.

Web presentation: https://docs.google.com/presentation/d/1PPpRHIZ41ehvlEf8zJqEl52pAA6c6Ml5mnE41EM_we0/pub?start=false&loop=false&delayms=3000

PDF: https://drive.google.com/file/d/0BxizCiVtZoVsTkF0Q3dSdkpqMDA/edit?usp=sharing

**Comment by jhilden** [comment]
looks really good.  but maybe we could add a slide with pictures from last year (can be taken from here #6)

**Comment by koos** [comment]
i’m working on it 

-----Original Message-----
